[versions]
kotlin = "2.4.0"
oskitKmp = "5.2.0-rc1"
composeMultiplatform = "1.11.1"
activityCompose = "1.13.0"
coreKtx = "1.18.0"
junit = "4.13.2"
koin = "4.2.2"
ktor-client-core = "3.5.0"
lifecycleProcess = "2.10.0"
markdown = "0.7.5"
okio = "3.17.0"
kotlinx-atomicfu = "0.33.0"
kotlinx-datetime = "0.8.0"
kotlinx-coroutines-core = "1.11.0"
kotlinx-browser = "0.5.0"
dokka = "2.2.0"
material-icons = "1.7.3"
android-compileSdk = "36"
android-minSdk = "28"
androidGradlePlugin = "9.0.1"
navigationEvent = "1.1.2"
navigationEventCompose = "1.1.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-client-core" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-client-core" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor-client-core" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor-client-core" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
oskit-kmp = { module = "com.outsidesource:oskit-kmp", version.ref = "oskitKmp" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "composeMultiplatform" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
navigationEvent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "navigationEventCompose" }
navigationEvent = { module = "androidx.navigationevent:navigationevent", version.ref = "navigationEvent" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }