name: Package Publish CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v3
    - name: Set Run ID
      run: |
        echo "OS_DEVELOPER=${{ secrets.OSD_DEVELOPER }}" >> $GITHUB_ENV
        echo "OS_TOKEN=${{ secrets.OSD_TOKEN }}" >> $GITHUB_ENV
        echo "GITHUB_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64

    - name: Publish Package
      run: gradle publish --no-daemon

  create_release:
    needs: build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v3
    - name: Read Version Properties
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './version.properties'
        property: 'version'
    - name: Print Version
      run: echo ${{ steps.read_property.outputs.value }}

    - name: Tag Release
      run: |
        git config --local user.email developer@outsidesource.com
        git config --local user.name "SD Developer"
        git tag v${{ steps.read_property.outputs.value }}
        git push --tags

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.read_property.outputs.value }}
        release_name: Release v${{ steps.read_property.outputs.value }}
        body: sed -e 's/:/\n/g' ./notes.txt
        draft: false
        prerelease: false