name: Publish Dokka
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Build documentation
        run: ./gradlew dokkaHtml
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          BRANCH: gh-pages
          FOLDER: build/dokka/html
          token: ${{ secrets.OS_TOKEN }}