# This is a basic workflow to help you get started with Actions

name: Develop CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Increment Patch Version
      run: ./gradlew incrementPatch

      # Fetch SemVer for tagging
    - name: Read Properties
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './version.properties'
        property: 'version'

    - name: Commit changes
      run: |
        git config --local user.email developer@outsidesource.com
        git config --local user.name "OS Developer"
        git commit -am "[skip ci] version patch bump to v${{steps.read_property.outputs.value}}"

    - name: Push Changes
      run: git push
